// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} letter
 * @returns {Promise.<void>}
 */
export async function addLetter(letter) {
	// BEGIN USER CODE
	if(currentTile < 5 && currentRow < 6){
		const mxTile = document.querySelector('.mx-name-guessRow_'+ currentRow + '_tile_' + currentTile)
		guesses[currentRow][currentTile] = letter
		mxTile.textContent = letter
		mxTile.setAttribute('data',letter)
		currentTile++
	}
	// END USER CODE
}
