// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";

// BEGIN EXTRA CODE

	const showMessage = (message) => {
		const messageElement = document.createElement('p')
		messageElement.textContent = message
		const messageDisplay = document.querySelector('.message-container')
		messageDisplay.append(messageElement)
		setTimeout(()=> messageDisplay.removeChild(messageElement),2000 )
	}
	
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function checkRow() {
	// BEGIN USER CODE

	const guess = guesses[currentRow].join('')
	console.log(currentTile)
	console.log(guess)
	console.log(word)
	if(currentTile === 5) {
		if ( word == guess ) {
			showMessage('Topzeraaaaaa')
			isGameOver = true
		} else {
			
			if(currentRow >= 5) {
				isGameOver = false
				showMessage('Game Over My Friend!!')
				return
			}
			if(currentRow < 5 ){
				currentRow++
				currentTile = 0
			}
	   }
	} 
	// END USER CODE
}
